### ISSUE TITLE
Improve Factory Provider with libffi

### ISSUE THREAD

**Issue by drodriguez** [appsquickly/Typhoon#102]
The Factory Provider should allow to type a lot less of code. Currently the user has to manually provide a lot of code blocks for each of the factory methods. It maybe possible to do more work automatically for the user, at least for the simple cases.
## Example

For a class and a factory like the following:

``` objc
@interface Payment : NSObject
- (instancetype)initWithCreditService:(id<CreditService>)creditService
                          authService:(id<AuthService>)authService
                            startDate:(NSDate *)date
                                amout:(NSUInteger)amount;
@end

@protocol PaymentFactory <NSObject>
@property (nonatomic, strong, readonly) id<CreditService> creditService;
@property (nonatomic, strong, readonly) id<AuthService> authService;
+ (Payment *)paymentWithStartDate:(NSDate *)startDate
                           amount:(NSUInteger)amount;
@end
```

I want to be able to generate the `PaymentFactory` implementation with the following
definition.

``` objc
- (id)paymentFactory {
  return [TyphoonFactoryProvider withProtocol:@protocol(PaymentFactory) dependencies:^(TyphoonDefinition *definition) {
    [definition injectProperty:@selector(creditService)];
    [definition injectProperty:@selector(authService)];
  } returningType:[Payment class]];
}
```

Using some conventions (which are pretty usual), the implementation of `paymentWithStartDate:amount:` should be a little bit of argument shuffling and forwarding to the `Payment` class.
## Explanation

For this simple factories we need first to map the relation between the factory method and the constructor to be used.

```
@selector(paymentWithStartDate:amount:) ---> @selector(initWithCreditService:authService:startDate:amount:)
```

We will also need a way to map the relation between input arguments/properties and the initializer arguments.

```
1st argument -> property "creditService"
2nd argument -> property "authService"
3rd argument -> 1st input argument
4th argument -> 2nd input argument
```

(There will be another kind of argument “constant”)

The argument types must be the same for input and initializer, so the code doesn’t do any transformation.

Something like this could be the internal API (that might be also exposed):

``` objc
[[definition factoryMethod:@selector(paymentWithStartDate:amount:) type:[Payment class]]
    initWithCreditService:TyphoonFactoryInjectProperty(creditService)
    authService:TyphoonFactoryInjectProperty(authService)
    startDate:TyphoonFactoryInjectArgument(0)
    amout:TyphoonFactoryInjectArgument(1)];
```

(Those “functions” are actually macros which will create the right classes, something like `TyphoonFactoryProviderInvocationArgument`. Also, I will use a proxy to allow the
inline definition of the arguments. I can also implement the more Typhoon-esque way, if people prefer that:)

``` objc
// Alternative Typhoon-esque way?
[[definition factoryMethod:@selector(paymentWithStartDate:amount:)
  type:[Payment class]
  withInitializer:^(TyphoonFactoryInitializerBlock *initializer) {
    initializer.selector = @selector(initWithCreditService:authService:startDate:amount:);
    [initializer injectWithProperty:@selector(creditService)];
    [initializer injectWithProperty:@selector(authService)];
    [initializer injectWithArgumentAtIndex:0];
    [initializer injectWithArgumentAtIndex:1];
}];
```

(This is very similar to `TyphoonInitializerBlock`, but it cannot be the same, so that’s my main reason to not follow Typhoon-esque patterns for this, but it can share a lot of code, but need two totally different set of valid “injections”. Anyway, that’s a lot more typing than the block, so people will probably not use it).

After finishing the definition block, there will be a couple of checks (number of factory methods defined, methods existing in protocols, initializer existing in classes, right number of arguments…). All those checks will fail at runtime, probably.
## Automatic wiring

The simplest case is one factory method and one initializer. We could have supposed that the input arguments are in the same order than the output arguments, but since the properties of a class do not specify the order in which they are returned, we cannot use the order for the first arguments. In the end is better, because we use a more general solution, which solves a lot more situations.

The idea is “parsing” the usual conventions for the initializer and the factory methods used in Cocoa. We will have a set of rules that will be used. If you follow other rules, or your factory method/initializer needs another name, no problem, you can always use the “manual” mapping definition.

For the factory methods we will remote everything until the first “With” and convert every atom of the selector to `lower camelCase` removing the colons (so `paymentWithStartDate:amount:` will end up as `@[@"startDate", @"amount"]`). For the initializer is the same, but we take out the “initWith” prefix (so `initWithCreditService:authService:startDate:amount:` ends up as `@[@"creditService", @"authService", @"startDate", @"amount"]`).

At this moment, we will try to create the mappings comparing the name of the atoms. If there is still mappings to fill, we will then look at the property names (that way and argument with the same name as a property will override the property, which I think is expected).

In our running example, first we will assign input argument at index 0 with output argument at index 2, and input argument at index 1 with output argument at index 3. Since two arguments are still not set, we will look at the properties and fill property “creditService” with output argument at index 0, and “authService” with output argument at index 1.

For the case of several factory methods and initializer, I suppose one can follow the same pattern, testing which one of the initializers fits better the factory method. However I going to left that as a low priority requirement.

As you can see the “conventions” are not that strange (if your own factory methods and initializers use different namings, you have bigger problems). Using the same name for the properties and the selector atoms is not that strange, either.
## Ending notes, questions & comments

I will start developing in drodriguez/Typhoon following the branch factory-providers. I will probably keep an ongoing pull request in this repository, so we all can comment.

We need libffi. I have found that https://github.com/zwaldowski/libffi-iOS offers a podspec, so I will need to include a dependency in Typhoon podspec. I suppose that’s not a problem (I don’t want to namespace all libffi).

Any questions, suggestions, ideas, or things I might overlook?
## Tasks
- [x] Integrate with libffi (https://github.com/zwaldowski/libffi-iOS)
- [x] Create classes supporting definition of the mappings
- [x] Implement libffi code to forward arguments to the right functions.
- [x] Implement heuristics for automatic wiring of simple cases.
- [x] Implement heuristics for automatic wiring of complex cases (optional).
